version: '3'
services:
  nodejs-server:
    build:
      context: ./node-users-miracle
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
       - ./node-users-miracle:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui:
    build:
      context: ./angular-users-miracle
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - ./angular-users-miracle:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules